### ISSUE TITLE
RMSE calculation

### ISSUE THREAD

**Issue by MOshima-PIFSC** [jabbamodel/ss3diags#3]
In the SSplotJABBAres function, I believe there is an error when the RMSE is calculated for the output table (lines 262-266). 
```
 rmse.i =  ni = NULL
    for(i in 1:n.indices){
      res.i =sum(Resids[1,]^2,na.rm =TRUE)
      ni[i] =length(as.numeric(Resids[i,])[is.na(as.numeric(Resids[i,]))==FALSE])
      rmse.i[i] = round(100*sqrt(res.i/ni[i]),1)
    }
```
Instead of `res.i =sum(Resids[1,]^2,na.rm =TRUE)`, I believe it should be `res.i =sum(Resids[i,]^2,na.rm =TRUE)` so that each row of residuals is indexed instead of only using the first row to calculate RMSE for each fleet.

**Comment by jabbamodel** [comment]
Thanks. Issue is fixed.  Luckily it only affected the RMSE by index not the joint one shown in the plot but still....the table was wrong. 
I must start checking my issues. Clearly not on top of it.
